config/routes.rb
Livepost::Application.routes.draw do
  root to: 'static_pages#home'

  match '/help',  to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/signup', to: 'identities#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: 'sessions#failure', via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post, :delete]

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :identities, only: [:new]

  match '/browse', to: 'chatlogs#index', via: 'get', as: 'chatlogs'
  match '/newpublicchat', to: 'chatlogs#newpublic', via: 'get', as: 'newpublic'
  match '/createpublic', to: 'chatlogs#createpublic', via: 'post', as: 'createpublic'
  match '/:id/deletechat', to: 'chatlogs#destroy', via: 'get', as: 'deletechat'
  match '/:id/leftchat', to: 'chatlogs#leftchat', via: 'get', as: 'leftchat'

  resources :chatlogs, path: "", except: [:edit], param: :id do
      resources :chatposts, only: [:show, :create, :destroy]
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  #don't require login for these pages, as they are public
  skip_before_filter :require_login

  def home
    # If visitor is signed in, redirect to Chats index
    if current_user and !current_user.name.include?("guest_")
      @publicchats = Chatlog.where('privatechat = ?', false).order('chatname DESC') rescue nil
      @privatechatsallowed = Chatlog.where('privatechat = ? AND permitted LIKE ?', true, "%#{current_user.id}%").order('chatname DESC') rescue nil
      return render 'chatlogs/index'
    end
  end

end

app/views/static_pages/home.html.erb
<!-- header -->
<div id="top" class="header">
  <div class="vert-text">
    <a href="https://github.com/slacker87/livepost"><img style="position: absolute; top: 0; left: 0; border: 0; width: 149px; height: 149px;" src="http://aral.github.com/fork-me-on-github-retina-ribbons/left-red@2x.png" alt="Fork me on GitHub"></a>
    <h1>livepost</h1>
    <h4 align="center" style="color:red;font-weight:bold;position:relative;top:-65px;right:-135px;display:inline;">alpha</h4>
    <div id="buttons" style="margin-top:15px;">
      <!-- Button trigger modal -->
      <button class="btn btn-default btn-lg" data-toggle="modal" data-target="#loginModal">
        Sign in
      </button>
      <h4>
      	Or
      </h4>
      <%= link_to "Browse Chats", chatlogs_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
</div>
<!-- /header -->
<!-- Intro -->
<div id="about" class="intro">
  <div class="container">
    <div class="row">
      <div class="col text-center">
        <h3 align="center">Livepost.io offers a unique community of social like-minded individuals whom like to talk to others. It's easy, fun, and entertaining. Simply, a nice place to chat. So introduce yourself to some new folks, invite you friends, and get the party started!</h3>
      </div>
    </div>
  </div>
</div>
<!-- /Intro -->

<!-- Call to Action -->
<div class="call-to-action">
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1 text-center">
        <h3>What are you waiting for? <%= link_to "Join today!", signup_path %></h3>
      </div>
    </div>
  </div>
</div>
<!-- /Call to Action -->


<!-- sign in modal -->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Login</h4>
      </div>
      <div class="modal-body">
          <%= form_tag "/auth/identity/callback" do %>
          <div class="control-group short-control-group" align="center">
          	<%= label_tag :auth_key, "Email" %>
          	<div align="center" style="margin-top:-5px;">
              <%= text_field_tag :auth_key, nil, class: 'form-control' %>
            </div>
          </div>
          <div class="control-group short-control-group" style="margin-top:5px;" align="center">
          	<%= label_tag :password %>
          	<div align="center" style="margin-top:-5px;">
              <%= password_field_tag :password, nil, class: 'form-control' %>
          	</div>
          </div>
          <div align="center" style="margin-top:5px;width: 300px;margin-left: 120px;">
            <%= submit_tag "Login", class: "btn btn-primary btn-block" %>
          </div>
        <% end %>
        </div>
      <div class="modal-footer" style="padding-top:10px;padding-bottom:10px;" align="center">
          <%= link_to "Create a new account", new_identity_path, class: 'btn btn-block btn-default btn-xs' %>
      </div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->



<!-- for pretty scroll down action -->
<script>
  $(function() {
    $('a[href*=#]:not([href=#])').click(function() {
      if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'')
          || location.hostname == this.hostname) {
        var target = $(this.hash);
        target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
        if (target.length) {
          $('html,body').animate({
            scrollTop: target.offset().top
          }, 1000);
          return false;
        }
      }
    });
  });
</script>