config/routes.rb
Livepost::Application.routes.draw do
  root to: 'static_pages#home'

  match '/help',  to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/signup', to: 'identities#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: 'sessions#failure', via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post, :delete]

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :identities, only: [:new]

  match '/browse', to: 'chatlogs#index', via: 'get', as: 'chatlogs'
  match '/newpublicchat', to: 'chatlogs#newpublic', via: 'get', as: 'newpublic'
  match '/createpublic', to: 'chatlogs#createpublic', via: 'post', as: 'createpublic'
  match '/:id/deletechat', to: 'chatlogs#destroy', via: 'get', as: 'deletechat'
  match '/:id/leftchat', to: 'chatlogs#leftchat', via: 'get', as: 'leftchat'

  resources :chatlogs, path: "", except: [:edit], param: :id do
      resources :chatposts, only: [:show, :create, :destroy]
  end
end

app/models/chatlog.rb
class Chatlog < ActiveRecord::Base
  has_many :chatpost, dependent: :destroy

  validates :chatname, presence: true
  validates :slug, uniqueness: true

  serialize :administrators
  serialize :permitted
  serialize :usershere

  # Generate random hash string to be used as slug
  before_save { self.slug ||= Digest::MD5.hexdigest(rand(999999999).to_s)[0..8] }

  #default_scope -> {order('created_at DESC')}

  # Override default find method to use slug rather than id
  def self.find(slug)
    find_by_slug(slug)
  end

  # Change default param for chatlog from id to slug for security/anonymity
  def to_param
    slug
  end
end

app/controllers/chatlogs_controller.rb
class ChatlogsController < ApplicationController
  require 'json'

  def index
    @publicchats = Chatlog.where('privatechat = ?', false).order('chatname DESC') rescue nil
    @privatechatsallowed = Chatlog.where('privatechat = ? AND permitted LIKE ?', true, "%#{current_user.id}%").order('chatname DESC') rescue nil
  end

  def create
    chatlog = Chatlog.new(params[:chatlog])
    chatlog[:chatname] = params[:chatparams][:chatname]
    chatlog[:administrators] = [current_user.id]
    chatlog[:permitted] = current_user.id
    chatlog[:privatechat] = true
    chatlog[:created_by] = current_user.name
    chatlog[:users_here] = []

    if chatlog.save
      return redirect_to chatlog, :flash => {:success => "Successfully created chat" }
    else
      redirect_to new_chatlog_path, :flash => {:error => "Chat name cannot be blank"}
    end
  end

    def createpublic
      if current_user.admin != true
        return redirect_to root_path, :flash => {:error => "Only administrators can create new public chats"}
      end
    chatlog = Chatlog.new(params[:chatlog])
    chatlog[:chatname] = params[:chatparams][:chatname]
    chatlog[:administrators] = [current_user.id]
    chatlog[:permitted] = current_user.id
    chatlog[:privatechat] = false
    chatlog[:created_by] = current_user.name

    if chatlog.save
      return redirect_to chatlog, :flash => {:success => "Successfully created chat" }
    else
      redirect_to new_chatlog_path, :flash => {:error => "Chat name cannot be blank"}
    end
  end

  def new
    chatlog = Chatlog.new
  end

  def show
    @chat ||= Chatlog.find(params[:id])
    @posts ||= @chat.chatpost.includes(:user)
    @usershere = @chat.usershere
    if @usershere.nil?
      @usershere = []
      @chat.save!
    end
    if !@usershere.include?(current_user)
      @usershere << current_user
      @chat.save!
    end
  end

  def update
    @chat ||= Chatlog.find(params[:id])
    if params[:chatparams][:post] != ""
      post = ChatlogsHelper.makepost(@chat,params[:chatparams][:post],current_user)
    end
    if post.nil? == false
      @post = post
      return render 'update'
    end
    return render :nothing => true
  end

  def leftchat
    @chat ||= Chatlog.find(params[:id])
    @usershere = @chat.usershere
    @usershere.delete(current_user)
    @chat.save!
    return render 'leftchat'
  end

  def destroy
    Chatlog.find(params[:id]).destroy
    flash[:success] = "Chat deleted."
    return redirect_to root_path
  end

  
end

app/helpers/chatlogs_helper.rb
module ChatlogsHelper
  
  def self.makepost(chat, post, user)
    mypost = chat.chatpost.new
    mypost.user_name = user.name
    mypost.user_id = user.id
    mypost.post = post
    mypost.save
    user.update_attribute(:lastseen, DateTime.now)
    return mypost
  end
  
  
end

app/views/chatlogs/_chatlog.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation" style="width: 65%;margin-left: 15%;background-color: transparent;border-bottom: none;padding-top: 0; margin-top: -10px;">
	<!-- Brand and toggle get grouped for better mobile display -->
	<div class="navbar-header" style="width: 100%">
    <h1 class="chatlogtitle" style="width: 100%;" align="center"><b><%= @chat.chatname.titleize %></b></h1>
	</div>
</nav>
<div class="" style="padding-bottom: 0px; margin-bottom: 0px;height: 100%">
  <div class="panel panel-body chatscroll" style="overflow-y: hidden;overflow-x: hidden;width:100%;height: 100%;position: fixed;bottom: 185px;background-color:#fff;" id="chatscroll">
		<% if @posts.empty? %>
			No posts. Start the conversation!
		<% else %>
			<div style="padding-top: 80px;"></div>
			<% @posts.each do |post| %>
				<% user = post.user %>
    <div style="width: 95%;" class="sentpost" id="<%= post.id %>" style="background-color: #ddd" >
					<%= gravatar_for user %>
          <%= link_to user.name, user%>
      <br/>
          <% if current_user == post.user %>
            <%= auto_link(post.post) %>
      			<%= link_to "", chatlog_chatpost_path(@chat, post), method: :delete, remote: true, title: "Delete this post", class: "glyphicon glyphicon-remove", style: "float:right;margin-right:10px;padding-left:0px;margin-left:25px;" %>
          <% elsif current_user == nil %>
            <%= auto_link(post.post) %>  
          <% elsif (@chat.administrators.detect {|id| id == user.id}) or current_user.super_user == true %>
							<%= auto_link(post.post) %>
              <%= link_to "", chatlog_chatpost_path(@chat, post), method: :delete, remote: true, title: "Delete this post", class: "glyphicon glyphicon-remove", style: "float:right;margin-right:10px;padding-left:0px;margin-left:25px;" %>
          <% else %>
            <%= auto_link(post.post) %>      
      <% end %>
				</div>
            <% end %>
          <% end %>
    </div>
</div>
    
<script>
	document.getElementById('chatscroll').scrollTop = 9999999;
</script>

app/views/chatlogs/_newpost.html.erb
<%= javascript_include_tag "jquery-te-1.4.0.min" %>
<%= stylesheet_link_tag "jquery-te-1.4.0" %>

<div style="width: 100%;position: fixed; bottom:20px;height: 185px;">
  <div style="width: 100%; height: 156px;">
        <%= form_for :chatparams, url: chatlog_path(@chat),:method => :patch, :remote => true, :html => { :id => "newpost"} do |f| %>
              <%= f.text_area :post, class: "jqte", placeholder: "Enter new post", id: 'input-line', autofocus: true, :autocomplete => :off %>
  </div>
  <div style="width: 100%; height: 20px;position: fixed; bottom: 16px;">
    <%= submit_tag "Send", class: "btn btn-primary btn-block",style: "border-radius: 0px", disable_with: 'Sending…'  %>
  </div>
<% end %>
</div>

<script>
	$('.jqte').jqte();
	
	// settings of status
	var jqteStatus = true;
	$(".status").click(function()
	{
		jqteStatus = jqteStatus ? false : true;
		$('.jqte').jqte({"status" : jqteStatus})
	});
  
  $('.jqte_editor').focus();
</script>

app/views/chatlogs/_show.js.erb
<!-- set some variables for private_pub to know where things should go -->
<% @usersubscribe = "/#{@chat.id}/show" %>
<% @usershow = "/chatlogs/usershow" %>
<% @thisuser = current_user %>
<!-- publish the submitted form to the private_pub server -->
<% publish_to @usersubscribe do %>
  <!-- append the new submitted form to the chat box using ajax -->
  $("#userlist").append("<%= j render(@usershow) %>");
<% end %>

app/views/chatlogs/index.html.erb
<% provide(:title, "Browse Chats") %>
      <div class="panel panel-default" style="padding: 0; margin: 0;width: 60%;margin-left:20%;margin-top: 5%;">
        <div class="panel panel-body" style="background-color: #fff;">
          <h1 class="form-signin-heading"><b>Browse Chats</b></h1>
          <div align="center" style="max-height: 80%; overflow-y: hidden;" id="chatscroll">
            <!-- if there are no chats, let the user know -->
            <% if @publicchats.blank? and @privatechatsallowed.blank? %>
            	<p align="center">No chats active, <%= link_to "start a new chat",  new_chatlog_path %>?</p>
            <% else %>
            	<h4>Public Chats</h4>
            	<div class="list-group">
              		<!-- make sure we have public chats to actually show -->
              		<% if @publicchats.blank? or @publicchats.nil? %>
              			<div class="well">
                		<p>No public chats active, <%= link_to "start a new chat",  new_chatlog_path %>?</p>
              			</div>
              		<% end %>
              <!-- list all available public chats -->
              <% @publicchats.each do |chat|%>
                <!-- link to each chat -->
                <%= link_to chat, class: "list-group-item", style: "padding: 0;background-color: #fff;" do %>
                <!-- add a nice popover to view the latest post -->
                <div style="height: 50px;" data-toggle="popover-bottom" data-content='
                                                                   <% if chat.chatpost.last != nil %>
                                                                     Latest post:
                                                                     <%= chat.chatpost.last.post %>
                                                                   <% else %>
                                                                     No new posts
                                                                   <% end %>
                '>
                  <!-- div to properly format list-item text -->
                  <div style="padding-top:15px;padding-left: 15px;padding-right: 15px;">
                    <h4 class="list-group-item-heading" style="float: left;"><%= chat.chatname.titleize %></h4>
                    <p class="list-group-item-text" style="display: inline-block; float: right;font-size: 11px;margin-top:7px;">
                      Started on <%= chat.created_at.to_s.to_datetime.strftime('%D %H:%M ') %>
                    </p>
                  </div>
                </div>
                <% end %>
                   <!-- if user is an admin or super admin, allow them to delete the chat -->
              <div style="padding-bottom: 35px;">
                    <% if current_user != nil and (chat.administrators.detect {|id| id == current_user.id}) or  current_user != nil and current_user.super_user == true %>
                      <%= link_to "Delete", deletechat_path(chat), title: "Delete this chat", data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-xs", style: "display: inline-block;margin-left: 20px;float: right;" %>
                    <% end %>
              </div>
              <% end %>
              <!-- end list all public chats -->
            </div>

            <h4>Private Chats</h4>

            <div class="list-group">
              <!-- make sure we have private chats to actually show -->
              <% if @privatechatsallowed.blank? or @privatechatsallowed.nil? %>
              <div class="well" style="padding: 10px;padding-bottom: 5px;">
          		<% if  current_user != nil and !current_user.name.include?("guest_") %>
                <p align="center" style="margin-top: 5px;">No private chats active, <%= link_to "start a new private chat",  new_chatlog_path %>?</p>
              	<% else %>
              		<p align="center">Private chats not allowed for guest accounts </p>
              	<% end %>
              </div>
              <% else %>
              <!-- list all available private chats -->
              <% @privatechatsallowed.each do |chat| %>
                <!-- link to each chat -->
                <%= link_to chat, class: "list-group-item", style: "padding: 0;background-color: #fff;" do %>
                <!-- add a nice popover to view the latest post -->
                <div style="height: 50px;" data-toggle="popover-top" data-content='
                                                                   <% if chat.chatpost.last != nil %>
                                                                     Latest post:
                                                                     <%= chat.chatpost.last.post %>
                                                                   <% else %>
                                                                     No new posts
                                                                   <% end %>
                '>
                  <!-- div to properly format list-item text -->
                  <div style="padding-top:15px;padding-left: 15px;padding-right: 15px;">
                    <h4 class="list-group-item-heading" style="float: left;"><%= chat.chatname.titleize %></h4>
                    <p class="list-group-item-text" style="display: inline-block; float: right;font-size: 11px;margin-top:7px;"> Started on <%= chat.created_at.to_s.to_datetime.strftime('%D %H:%M ') %> by <%= chat.created_by %>
                    </p>
                  </div>
                </div>
              <% end %>
                    <!-- if user is an admin or super admin, allow them to delete the chat -->
              <div style="padding-bottom: 35px;">
                    <% if current_user != nil and (chat.administrators.detect {|id| id == current_user.id}) or  current_user != nil and current_user.super_user == true %>
                      <%= link_to "Delete", deletechat_path(chat), title: "Delete this chat", data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-xs", style: "display: inline-block;margin-left: 20px;float: right;" %>
                    <% end %>
              </div>
              <% end %>
              <!-- end list all private chats -->
            </div>
            <% end %>

            <% end %>
            <!-- end of chat list section -->

          </div>
          <% if  current_user != nil and !current_user.name.include?("guest_") %>
          <p style="margin-top: 50px;width: 80%;margin-left: 10%"><%= link_to "Start a new chat!", new_chatlog_path, class: "btn btn-primary btn-block" %></p>
          <% end %>
          <% if  current_user != nil and current_user.admin == true %>
          	<p style="margin-top: 50px;width: 80%;margin-left: 10%"><%= link_to "Start a new public chat", newpublic_path, class: "btn btn-primary btn-block" %></p>
          <% end %>
        </div>
      </div>

app/views/chatlogs/leftchat.js.erb
<!-- set some variables for private_pub to know where things should go -->
<% chatsubscribe = "/#{@chat.id}/update" %>
<!-- publish the submitted form to the private_pub server -->
<% publish_to chatsubscribe do %>
  $('#<%= current_user.id %>').remove();
<% end %>

app/views/chatlogs/new.html.erb
<% provide(:title, "New Chat") %>

<div class="chatlognew">
  <row>
    <div class="col-md-6 col-md-offset-3" style="padding-top:5px;margin-top: 10%;">
      <div class="panel panel-default">
        <div class="panel panel-body" style="background-color: #fff;">
          <h1 class="form-signin-heading"><b>Start a New Chat</b></h1>
          <div width="100%">
            <%= form_for :chatparams, url: {action: "create"}, class: "form-signin" do |f| %>
            <%= f.label :chatname, "Chat name", class: "label label-default" %>
            <%= f.text_field :chatname, class: "form-control", placeholder: "Enter chat name here" %>
            <br />
            <br />
            <div align="center">
              <%= f.submit "Create", class: "btn btn-large btn-primary btn-block"  %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </row>
</div>

app/views/chatlogs/newpublic.html.erb
<% provide(:title, "New Public Chat") %>

<div class="chatlognew">
  <row>
    <div class="col-md-6 col-md-offset-3" style="padding-top:5px;margin-top: 10%;">
      <div class="panel panel-default">
        <div class="panel panel-body" style="background-color: #fff">
          <h1 class="form-signin-heading"><b>Start a new public chat</b></h1>
          <div width="100%">
            <%= form_for :chatparams, url: {action: "createpublic"}, class: "form-signin" do |f| %>
            <%= f.label :chatname, "Chat name", class: "label label-default" %>
            <%= f.text_field :chatname, class: "form-control", placeholder: "Enter chat name here" %>
            <br />
            <br />
            <div align="center">
              <%= f.submit "Create", class: "btn btn-large btn-primary btn-block"  %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </row>
</div>

app/views/chatlogs/show.html.erb
<% provide(:title, @chat.chatname.titleize) %>

<% content_for :header do %>
  <%= javascript_include_tag "chatlogs" %>
<% end %>

<!-- check if the user is an admin -->
<% if @chat.administrators.include?(current_user) then %>
	<%= render 'admin/chatadmin' %>
<% end %>

<!-- render the chatlog, userlist, and new post sections -->
<%= render 'chatlogs/chatlog' %>
<%= render 'chatlogs/side/userlist' %>
<%= render 'chatlogs/side/invite' %>
<%= render 'chatlogs/newpost' %>

<!-- subscribe to this chat so the user can see private_pub AJAX updates -->
<%= @subscribedtochat = subscribe_to "/#{@chat.id}/update" %>

<!-- subscribe to the current users list -->
<%= @subscribedtousers = subscribe_to "/#{@chat.id}/show" %>

<script>
//for the path when a user unloads
var leftchatpath = "<%= leftchat_path(@chat) %>";
</script>

app/views/chatlogs/show.js.erb
<!-- set some variables for private_pub to know where things should go -->
<% @usersubscribe = "/#{@chat.id}/show" %>
<% @usershow = "/chatlogs/usershow" %>
<% @thisuser = current_user %>
<!-- publish the submitted form to the private_pub server -->
<% publish_to @usersubscribe do %>
  <!-- append the new submitted form to the chat box using ajax -->
  $("#userlist").append("<%= j render(@usershow) %>");
<% end %>

app/views/chatlogs/update.js.erb
<!-- publish the submitted form to the private_pub server -->
<% publish_to "/#{@chat.id}/update" do %>
	<!-- append the new submitted form to the chat box using ajax -->
	$("#chatscroll").append("<%= j render("/chatposts/show") %>");
	<!-- This script will auto-scroll the chat window to the lastest post -->
	document.getElementById('chatscroll').scrollTop = 9999999;
<% end %>
$("#newpost")[0].reset();
$('.jqte').jqteVal("");
$('.jqte_editor').focus();