config/routes.rb
Livepost::Application.routes.draw do
  root to: 'static_pages#home'

  match '/help',  to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/signup', to: 'identities#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: 'sessions#failure', via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post, :delete]

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :identities, only: [:new]

  match '/browse', to: 'chatlogs#index', via: 'get', as: 'chatlogs'
  match '/newpublicchat', to: 'chatlogs#newpublic', via: 'get', as: 'newpublic'
  match '/createpublic', to: 'chatlogs#createpublic', via: 'post', as: 'createpublic'
  match '/:id/deletechat', to: 'chatlogs#destroy', via: 'get', as: 'deletechat'
  match '/:id/leftchat', to: 'chatlogs#leftchat', via: 'get', as: 'leftchat'

  resources :chatlogs, path: "", except: [:edit], param: :id do
      resources :chatposts, only: [:show, :create, :destroy]
  end
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
<div class="alert <%= bootstrap_class_for(type) %> fade in" align="center" style="width: 50%;margin-left:25%;">
  <button class="close" data-dismiss="alert" style="margin-right: 15px;margin-left:30px;">×</button>
  <%= message %>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer>
  <div class="col-md-10">
    <%= link_to "Home", root_url %>
  </div>
  <div style="col-md-2">
    <ul class="list-inline text-right">
      <li><i class="fa fa-facebook fa-3x"></i></li>
      <li><i class="fa fa-twitter fa-3x"></i></li>
    </ul>
  </div>
  <div class="col-md-12">
    <a href="https://github.com/slacker87/livepost">Livepost</a> is a collaborative project by
    <a href="https://github.com/slacker87"> Slacker87</a>,
    <a href="https://github.com/kcombs"> KCombs</a>,
    <a href="https://github.com/harrisongill"> harrisongill</a>,
    and <a href="https://github.com/stuarthannig"> stuarthannig</a>
  </div>
</footer>
<!-- /Footer -->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_sidemenu.html.erb
<a id="menu-toggle" class="btn btn-primary btn-lg toggle" style="background-color: #428BCA"><i class="fa fa-bars"></i></a>
    <div id="sidebar-wrapper" class="leather">
      <ul class="sidebar-nav">
        <a id="menu-close" class="btn btn-default btn-lg pull-right toggle"><i class="fa fa-times"></i></a>
        <li class="sidebar-brand"><%= link_to "LivePost", root_url %></li>
        <% if current_user.nil? or current_user.name.include?("guest_") %>
          <li><%= link_to "Browse Chats", chatlogs_path %></li>
          <hr>
          <li><%= link_to "Sign In", signin_path %></li>
          <li><%= link_to "Sign Up", signup_path %></li>
        <% else %>
          <li><%= link_to "Browse Chats", chatlogs_path %></li>
          <li><%= link_to "Start a Chat", new_chatlog_path %></li>
          <hr>
          <li><%= link_to "My Profile", current_user %></li>
          <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
        <% end %>
      </ul>
    </div>
<script>
$("#menu-close").click(function(e) {
	e.preventDefault();
	$("#sidebar-wrapper").toggleClass("active");
});
$("#menu-toggle").click(function(e) {
	e.preventDefault();
	$("#sidebar-wrapper").toggleClass("active");
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
"data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>
  <body>
    <%= render partial: "layouts/sidemenu" %>
    <%= render partial: "layouts/flash_messages", flash: flash %>
    <%= yield %>
  </body>
</html>